/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BerriesBerryIdRouteImport } from './routes/berries.$berryId'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BerriesBerryIdRoute = BerriesBerryIdRouteImport.update({
  id: '/berries/$berryId',
  path: '/berries/$berryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/eventos': typeof EventosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tienda': typeof TiendaRoute
  '/berries/$berryId': typeof BerriesBerryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/eventos': typeof EventosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tienda': typeof TiendaRoute
  '/berries/$berryId': typeof BerriesBerryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/eventos': typeof EventosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tienda': typeof TiendaRoute
  '/berries/$berryId': typeof BerriesBerryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/eventos'
    | '/reset-password'
    | '/tienda'
    | '/berries/$berryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/eventos'
    | '/reset-password'
    | '/tienda'
    | '/berries/$berryId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/eventos'
    | '/reset-password'
    | '/tienda'
    | '/berries/$berryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EventosRoute: typeof EventosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TiendaRoute: typeof TiendaRoute
  BerriesBerryIdRoute: typeof BerriesBerryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berries/$berryId': {
      id: '/berries/$berryId'
      path: '/berries/$berryId'
      fullPath: '/berries/$berryId'
      preLoaderRoute: typeof BerriesBerryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EventosRoute: EventosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TiendaRoute: TiendaRoute,
  BerriesBerryIdRoute: BerriesBerryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
