/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BerriesBerryIdRouteImport } from './routes/berries.$berryId'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BerriesBerryIdRoute = BerriesBerryIdRouteImport.update({
  id: '/berries/$berryId',
  path: '/berries/$berryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eventos': typeof EventosRoute
  '/tienda': typeof TiendaRoute
  '/berries/$berryId': typeof BerriesBerryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/eventos': typeof EventosRoute
  '/tienda': typeof TiendaRoute
  '/berries/$berryId': typeof BerriesBerryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eventos': typeof EventosRoute
  '/tienda': typeof TiendaRoute
  '/berries/$berryId': typeof BerriesBerryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/eventos' | '/tienda' | '/berries/$berryId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/eventos' | '/tienda' | '/berries/$berryId'
  id: '__root__' | '/' | '/eventos' | '/tienda' | '/berries/$berryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventosRoute: typeof EventosRoute
  TiendaRoute: typeof TiendaRoute
  BerriesBerryIdRoute: typeof BerriesBerryIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berries/$berryId': {
      id: '/berries/$berryId'
      path: '/berries/$berryId'
      fullPath: '/berries/$berryId'
      preLoaderRoute: typeof BerriesBerryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventosRoute: EventosRoute,
  TiendaRoute: TiendaRoute,
  BerriesBerryIdRoute: BerriesBerryIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
